[package]
name = "rust_chat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-bigint = { version = "0.2.2", features = ["rand"] }
rand = "0.6.5"
num-traits = "0.2"
num = "0.4.0"
