/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package Parsing;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INT = 1;
  /** RegularExpression Id. */
  int LET = 2;
  /** RegularExpression Id. */
  int ID = 3;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int MINUS = 5;
  /** RegularExpression Id. */
  int TIMES = 6;
  /** RegularExpression Id. */
  int DIVIDE = 7;
  /** RegularExpression Id. */
  int SEMICOLON = 8;
  /** RegularExpression Id. */
  int ASSIGNEQ = 9;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<INT>",
    "\"let\"",
    "<ID>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\";\"",
    "\"=\"",
    "\" \"",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
  };

}
